### ISSUE TITLE
Merge Sort in C#

### ISSUE THREAD

**Issue by deepansha-singh** [CodeChefMUST/DSA#126]
# Important:

Before you start your work on this issue, **make sure** you go through the README.md and Contribution Guidelines.md

## File structure:
1. In the `Sorting` directory, and navigate to the sub-directory `Merge Sort`.
2. Create the `C#` directory in the `Merge Sort` directory.
3. Create the file `MergeSort.cs`.

Here's how the final structure should look like:
- Sorting
    - Bubble Sort
        - Algorithm.md
        - C++
        - C#
              - MergeSort.cs

## Before you create a pull request, if you observe that the folder Merge Sort has already been created, then please refrain from creating a new one, make some changes in your forked repository so that it matches with the current one and there are no conflicts.

# Note that all PRs are being checked for plagiarism, please refrain from indulging in any crooked means, we trust you!

We thank you for your contribution and time and we hope that you enjoy contributing to open source.

**Comment by hr080100** [comment]
I am a beginner and I would like to work on this issue, this will help me a lot. Please, assign me.
