### ISSUE TITLE
Graph Traversal: BFS in C++

### ISSUE THREAD

**Issue by deepansha-singh** [CodeChefMUST/DSA#137]
# Important:

Before you start your work on this issue, **make sure** you go through the README.md and Contribution Guidelines.md and 
# do not submit plagiarized code.

## File structure:
1. Within the `Traversal Algorithms` directory, create a new sub-directory `Graph Traversals`, if it doesn't exist already.
3. And another subdirectory in `Graph Traversals` with the name `BFS`.
4. In this directory, create one last directory `C++`

Here's how the final structure should look like:
- Traversal Algorithms
    - GraphTraversals
        - BFS
            - C++
                - BFS.cpp

### Please follow the *same* naming conventions as mentioned in this comment.

We thank you for your contribution and time and we hope that you enjoy contributing to open source.

**Comment by ashishlamsal** [comment]
I would like to work on this issue.
