### ISSUE TITLE
Graph Traversal: DFS in Python

### ISSUE THREAD

**Issue by deepansha-singh** [CodeChefMUST/DSA#141]
# Important:

Before you start your work on this issue, **make sure** you go through the README.md and Contribution Guidelines.md and 
# do not submit plagiarized code.

## File structure:
1. Within the `Traversal Algorithms` directory, create a new sub-directory `Graph Traversals`, if it doesn't exist already.
3. And another subdirectory in `Graph Traversals` with the name `DFS`.
4. In this directory, create one last directory `Python`

Here's how the final structure should look like:
- Traversal Algorithms
    - Graph Traversals
        - DFS
            - Python
                - DFS.py

### Please follow the *same* naming conventions as mentioned in this comment.

We thank you for your contribution and time and we hope that you enjoy contributing to open source.

**Comment by LiuSeeker** [comment]
Can I work on this this issue?
