### ISSUE TITLE
Create algorithm explanation file for Knapsack problem (check description) 

### ISSUE THREAD

**Issue by Taneesha-creates** [CodeChefMUST/DSA#26]
### Contents:
* Problem Statement
* Input / Output
* Explain algorithm
* Talk about subproblems 

### File Structure required:
1. Create Folder - Dynamic Programming (like current Searching, Sorting etc)
2. Create Sub Directory - Knapsack
3. Create file - algorithm.md (this is the main file you have to edit with contents mentioned above)

Refer to the README.md for more information, or check out the existing folders to get an idea.

**Comment by VishalAmbavade** [comment]
Hey @Taneesha-creates, can you assign me this issue?
