### ISSUE TITLE
Algorithm (no code) for Heap Sort

### ISSUE THREAD

**Issue by deepansha-singh** [CodeChefMUST/DSA#51]
# Important:

Before you start your work on this issue, **make sure** you go through the README.md and Contribution Guidelines.md

## File structure:
1. Create the `Heap Sort` directory in the current `Sorting` directory.
2. Create the file `Algorithm.md`.

Here's how the final structure should look like:
- Sorting
    - Heap Sort
        - Algorithm.md
        - C++

### Please follow the *same* naming conventions as mentioned in this comment.

# Before you create a pull request, if you observe that the folder Heap Sort has already been created, then please refrain from creating a new one, make some changes in your forked repository so that it matches with the current one and there are no conflicts.

# Note that all PRs are being checked for plagiarism, please refrain from indulging in any crooked means, we trust you!
We thank you for your contribution and time and we hope that you enjoy contributing to open source.

**Comment by kumar1508** [comment]
@Taneesha-creates I have made the PR . Please review it .
Should I add image also to the algorithm.md file of Heap Sort?
