### ISSUE TITLE
C++ code - bellman ford algorithm 

### ISSUE THREAD

**Issue by Taneesha-creates** [CodeChefMUST/DSA#59]
# Important:

Before you start your work on this issue, **make sure** you go through the README.md and Contribution Guidelines.md

## File structure:
1. Create the `Graph Algorithms` directory, **if** not already created.
2. Create the `Bellman Ford` sub directory the `Graph Algorithms` directory **if** not already created.
3. Create the `C++` directory in the `Bellman Ford` directory.
3. Create the file `Dijkstra.cpp`.

Here's how the final structure should look like:
- Graph Algorithms
    - Bellman Ford
        - Algorithm.md
        - C++
               - BellmanFord.cpp
        - Java
        - Python

### Please follow the *same* naming conventions as mentioned in this comment.

# Before you create a pull request, if you observe that the required folders have already been created, then please refrain from creating a new one, make some changes in your forked repository so that it matches with the current one and there are no conflicts.

# Note that all PRs are being checked for plagiarism, please refrain from indulging in any crooked means, we trust you!
We thank you for your contribution and time and we hope that you enjoy contributing to open source.

**Comment by adityawithdoublea** [comment]
Hi @Taneesha-creates! I'd like to contribute.
