### ISSUE TITLE
Ternary Search in C++

### ISSUE THREAD

**Issue by ritika728** [CodeChefMUST/DSA#65]
Please assign!

**Comment by deepansha-singh** [comment]
Assigned to @ritika728 
Please read through the guidelines carefully. Looking forward to your contributions!

It has been noted that this is your third currently open issue. It is to bring to your notice that you can only create ONE more issue assign request before any of the other PRs are merged :) Glad to have you!

**Comment by Meghwantsingh** [comment]
hello,I would like do this problem .

**Comment by Taneesha-creates** [comment]
Hi, @Meghwantsingh we appreciate your interest in this issue, however this has already been assigned, and no more contributors are required at the moment.

Feel free to create another issue you wish to work on, we hope you enjoy contributing to open source :)
