### ISSUE TITLE
Heap Sort with Java

### ISSUE THREAD

**Issue by OrchiDorchi** [CodeChefMUST/DSA#89]
I want to implement it. Please assign it to me.

**Comment by Asifa23** [comment]
I would like to contribute. Please assign @OrchiDorchi

**Comment by Taneesha-creates** [comment]
Hello @OrchiDorchi, this issue already exists and has been assigned. We request you to look for an issue that interests you, or create a new on **if** it does not exist.

Have a good time contributing :)

**Comment by Taneesha-creates** [comment]
@Asifa23 , this has already been assigned to you.
