### ISSUE TITLE
Add codechef oct21C challenge solutions

### ISSUE THREAD

**Issue by anuragnewbie** [CodeChefMUST/DSA#94]
HI! I would like to add the problem solutions of the October 21 month-long challenge that has completed a few days before.

**Comment by Taneesha-creates** [comment]
Hello @anuragnewbie, this repository focuses on algorithms, and we do not accept solutions of contests on this platform. 

We thank you for your interest, and hope that you can find an issue that interests you, or create an issue in this repository that fits the purpose. Have a good day :)
